### ISSUE TITLE
Don't require ws-worker keys to run migrations in prod

### ISSUE THREAD

**Issue by taylordowns2000** [OpenFn/lightning#2211]
When running OpenFn in production mode on kubernetes, some folks may choose to automatically run migrations using an `initContainer`:

```
initContainers:
        - name: migrate-demo
          image: *demoImage
          command: ["/app/bin/lightning", "eval", "Lightning.Release.migrate"]
```

You shouldn't have to pass in a whole bunch of worker secrets and keys to this container _only_ to run the migrations.

It would be great to be able to run migrations with the bare minimum in terms of secrets.
- db url (yes.)
- secret key base (maybe?)
- primary encryption key (maybe?)
