### ISSUE TITLE
Add a HEALTHCHECK to Dockerfile

### ISSUE THREAD

**Issue by stuartc** [OpenFn/lightning#2774]
### Details

All docker deployments should have heath checks built in, right now we have to specify the health check via the compose file.

Eg:

```yaml
    healthcheck:
      test: ["CMD", "curl", "--fail", "localhost:4000/health_check"]
      interval: 30s
      timeout: 10s
      retries: 5
```

### User acceptance criteria

Running the image without specifying the heath check should work automagically.
