### ISSUE TITLE
Fix aggressive CSS rule in app.css

### ISSUE THREAD

**Issue by elias-ba** [OpenFn/lightning#2807]
This rule in `assets/css/app.css` seems very aggressive and it is actually impacting the colors of nested divs. 

```css
  div > div {
    &:first-child {
      background-color: var(--primary-bg-dark);
    }
  }
```
