### ISSUE TITLE
Sync to github fails when special characters exist in credential names

### ISSUE THREAD

**Issue by taylordowns2000** [OpenFn/lightning#2808]
When syncing a project that uses a credential called "Taylor Mailchimp June '24" the sync fails.

<img width="1477" alt="Image" src="https://github.com/user-attachments/assets/ad833b06-007b-4d95-a8a7-0fac89856aa6" />

After exporting the project yaml, I can see that the yaml looks like this:

```yaml
credentials:
  "taylor@openfn.org-MailChimp-June'24":
    name: 'MailChimp June'24'
...
        add-to-drip-campaign:
        name: add to drip campaign
        adaptor: '@openfn/language-mailchimp@1.0.0'
        credential: 'taylor@openfn.org-MailChimp-June'24'
```

And VS code knows that this is invalid.

<img width="684" alt="Image" src="https://github.com/user-attachments/assets/7e06ebfa-6c4e-4ae3-8dcd-a5e9eb3162ee" />

We should fix this so that credential names are made safe for yaml on export/sync, and we should extend the error message in the sync action to give the user more information about _WHY_ their sync fails.
