### ISSUE TITLE
Extend provisioning to support collections at a project level

### ISSUE THREAD

**Issue by stuartc** [OpenFn/lightning#2830]
## Background

Lightning’s [Project Spec documentation](https://docs.openfn.org/documentation/deploy/portability#the-project-spec) outlines how to define and manage resources in a project.yaml file. However, we currently have no way to define Collections in the spec. Collections can be accessed (but not created) via the CLI ([see docs](https://docs.openfn.org/documentation/collections-cli)), and we’d like to add this functionality to our project.yaml so that everything can be configured in one place.

```yaml
# project.yaml
name: MyProject
collections:
  - name: my-first-collection
```

or

```yaml
# project.yaml
name: MyProject
collections:
  - my-first-collection
  # this is shorthand for name: my-first-collection
```

## Requirement

Extend the current provisioning API to handle a `collections` key on the root of the document. Parsing, validating and create/update/deleting collections in the same way other entities are handled.

## Open questions

Do we care about permissions? Can anyone who can create/update a workflow also create/delete a collection?

**Comment by midigofrank** [comment]
Hey @stuartc @josephjclark I'm having trouble trying to support the shorthand versions because the `merging` operation uses a key as the identifier.

This is what I have, which is similar to the other objects, and it seems to do the job

```yaml
name: openhie-project
description: null
collections:
  dummy:
    name: dummy
```
