### ISSUE TITLE
Node version drift between Dockerfiles and CircleCi

### ISSUE THREAD

**Issue by zeorin** [OpenFn/lightning#3004]
**Describe the bug**

Node versions between the Docker files and CircleCi diverge.

**Version number**

`v2.10.16`

I have reproduced this locally on main:

- [x] Yes
- [ ] No

**To Reproduce** Steps to reproduce the behavior:

`.circleci/config.yml`:

```yaml
      nodejs_version:
        description: NodeJS version
        type: string
        default: "22.12.0"
```

`Dockerfile` & `Dockerfile-dev`:
```docker
ARG NODE_VERSION=18.17.1
```

**Expected behavior**

These versions should be the same.
